services:
  app:
    build: .
    container_name: ai_knowledge_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    depends_on:
      - postgres
      - redis
      - qdrant
      
  bot:
    build: .
    container_name: ai_knowledge_bot
    command: ["python", "-m", "app.bot"]
    profiles: ["bot"]
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    depends_on:
      - app
      - postgres
      - redis
      - qdrant

  worker:
    build: .
    container_name: ai_knowledge_worker
    command: ["python", "-m", "app.worker"]
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    depends_on:
      - postgres
      - redis
      - qdrant


  postgres:
    image: postgres:17
    container_name: ai_knowledge_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: ai_knowledge_redis
    volumes:
      - redis_data:/data

  qdrant:
    image: qdrant/qdrant:latest
    container_name: ai_knowledge_qdrant
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  postgres_data:
  redis_data:
  qdrant_data:
