services:
  app:
    build: .
    container_name: ai_knowledge_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    depends_on:
      - postgres
      - redis
      - qdrant
      
  bot:
    build: .
    container_name: ai_knowledge_bot
    command: ["python", "-m", "app.bot"]
    profiles: ["bot"]
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    depends_on:
      - app
      - postgres
      - redis
      - qdrant

  worker:
    build: .
    container_name: ai_knowledge_worker
    command: ["python", "-m", "app.worker"]
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    depends_on:
      - postgres
      - redis
      - qdrant


  postgres:
    image: postgres:17
    container_name: ai_knowledge_postgres
    environment:
      POSTGRES_DB: aiknowledgeassistant
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: ai_knowledge_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  qdrant:
    image: qdrant/qdrant:latest
    container_name: ai_knowledge_qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  postgres_data:
  redis_data:
  qdrant_data:
